### ISSUE TITLE
Possible Change

### ISSUE THREAD

**Issue by clawconduce** [willfaught/gockle#1]
I used this briefly and made a change in my local copy that I thought was more flexible with mocking:

``` go
func flattenStatementAndArgs(statement string, arguments []interface{}) []interface{} {
    params := make([]interface{}, 0)
    params = append(params, statement)
    params = append(params, arguments...)
    return params
}

// Exec implements Session.
func (m SessionMock) Exec(statement string, arguments ...interface{}) error {
    return m.Called(flattenStatementAndArgs(statement, arguments)...).Error(0)
}
```

The main motivation for this this is so that sql arguments could be mock.Any() objects for things like timestamps for modified/created fields.

**Comment by willfaught** [comment]
Hi, @clawconduce. That would be really useful! Currently, you can do stuff like "for any set of arguments, do X". How could you do that with this kind of change? It seems like with the way go-mock works at the moment, you can either use mock.Any only for individual arguments — as you've shown above — or only for all of them as a whole — as it works now — but not both. Perhaps this is better addressed in go-mock itself by adding that capability for interface{} vararg functions? I'm interested in your thoughts.

Have you tried using mock.AnyIf? For example:

```
m.When("F", mock.AnyIf(func(v interface{}) bool { return v.([]interface{})[2].(string) == "test" }))
```

**Comment by willfaught** [comment]
(Incidentally, your idea spurred me to move all the Session `arguments` parameters to the end of the parameter lists for consistency and for simplicity where there are no arguments. I just pushed those changes.)

**Comment by clawconduce** [comment]
Good point.  I can see how both cases are useful, and it's either or.  I like the idea of putting something in go-mock that would cover both cases.  As a bonus, it looks like it would just be adding something that would break out of this loop: https://github.com/maraino/go-mock/blob/master/mock.go#L286

**Comment by willfaught** [comment]
OK, I'm going to close this issue. I see you opened a [go-mock issue](https://github.com/maraino/go-mock/issues/6) to continue the discussion there.

**Comment by willfaught** [comment]
See https://github.com/maraino/go-mock/commit/341395fb6b2653a9891dd7f5af8795c030509c30
