### ISSUE TITLE
API closer to gocql

### ISSUE THREAD

**Issue by clawconduce** [willfaught/gockle#2]
I created a "gockle-lite" for our testing that is very similar, but also mocks queries.  I also made the change I suggested in a previous issue for flattening args.  The flattening args should probably get removed to use the new `Slice` type in go-mock.

It's a pretty large change to the gockle API, but I thought I would share anyways.  I made a README to go along with it as well.

[conduce-gockle.zip](https://github.com/willfaught/gockle/files/271611/conduce-gockle.zip)

**Comment by willfaught** [comment]
Thanks for sharing. I omitted a query type that would match gocql.Query because it's one fewer type you have to mock, and it seemed to work having all the query stuff in Session. I'm curious: why did you find having a separate query type was better?

**Comment by clawconduce** [comment]
It was for 2 reasons, first, it made it super easy to port code - it was just `:%s/*gocql.Session/gockle.Session`, and 2nd it kept the results & arguments more separated which I thought was easier to read.  So for things like `Scan`, I thought it was clearer for the non-mocked code to have `&results` separated from the cql statement and arguments.

**Comment by willfaught** [comment]
Ah, that makes sense. I designed it from the perspective of starting fresh, whereas you're coming at it from already using gocql, which seems more likely to me. Perhaps there's more value in just mimicking the gocql interfaces exactly. Unfortunately, gocql method names are (IMO) inconsistent, so I hate to adopt them, but the ability to search/replace _is_ appealing. Do you favor keeping the same method names as well?

**Comment by willfaught** [comment]
Edit: Do you favor keeping the same gocql method names as well, or do you like the gockle names enough to make the extra search/replaces for them worth it?

**Comment by clawconduce** [comment]
Even with inconsistent names, I would favor the gocql names.  It's really appealing to only have to replace the `gocql.Session` with a `gockle.Session`.  Then the rest of the code is untouched, and also, everything else can be figured out by referring to the gocql docs, mailing lists, stackoverflow questions, etc.

**Comment by willfaught** [comment]
That makes sense. I suppose I could always have separate types that simplify the original API. I'll make the change. Thanks for your thoughts!

**Comment by clawconduce** [comment]
No problem!

**Comment by soldiershen** [comment]
@clawconduce  
Hi Claw,
I use your zip code(does not rely on willfaught's code right?)
 and find a Mock call missing error.Could you help me to explain it?
I copy you readme code.
log:

panic: Mock call missing for Query(

```
"select id from atlas.mock_test where id = ?",

int(1),
```

) 
func TestGetId(t *testing.T){
    myRet := 42
    mockQuery := common.MockQuery{}
    //Scan should set a variable and return an error - nil in this case
    mockQuery.When("Scan", mock.Any).ReturnToArgument(0, &myRet).Return(nil)
    session := &common.SessionMock{}
    session.When("Query", mock.Any).Return(mockQuery) //error
    result,error:=GetId(session)
    println(result)
    assert.True(t,error==nil)
    assert.True(t,result==1)
}

func GetId(session common.Session) (int,error) {
    var id int
    if err := session.Query(`select id from atlas.mock_test where id = ?`,
        1).Scan(&id); err != nil {
        return id,err
    }
    return id,nil
}

**Comment by willfaught** [comment]
Sorry about the delay doing this. Lost steam when I started another thing. Not sure when I'll be able to get to it.

**Comment by clawconduce** [comment]
Hey, I have not looked at this much since posting it (though I do have tests that use it).  I think the issue here is that the query expects 1 argument, but is getting 2 arguments.  So the easiest fix is to change the line with the `//error` to `session.When("Query", mock.Any, mock.Any).Return(mockQuery)`

If this is the case, the README should say something like:

```
...
session.When("Query", mock.Any).Return(mockQuery)
```

The number of arguments in the query should match the number of arguments passed to query in your code.  Bear in mind that the query itself is an argument.  For the example above, the call in the code being tested should look something like:  `session.Query("SELECT value from my_keyspace.my_table")`.

Here is an example with 1 argument passed to the cassandra:

```
session.When("Query", mock.Any, int64(1)).Return(mockQuery)
```

With the code being tested looking like:

```
session.Query("SELECT email from ks.users", int64(userID))
```

**Comment by soldiershen** [comment]
@clawconduce  yes,I correct it by doing 
session.When("Query", "select id from atlas.mock_test where id = ?",mock.Any).Return(mockQuery) 

Thanks

**Comment by soldiershen** [comment]
@willfaught  @clawconduce  a suggestion is that use regex to match sqls like https://github.com/DATA-DOG/go-sqlmock

**Comment by willfaught** [comment]
Sorry if any issues are unresolved. I haven't touched or used this code in a couple years and don't remember much about it, or plan to add to it at this point. Please feel free to fork the code under the license if needed.
