### ISSUE TITLE
How to mock ScanMap

### ISSUE THREAD

**Issue by jerome-laforge** [willfaught/gockle#3]
Hello,
I try to mock ScanMap (https://github.com/willfaught/gockle/blob/master/session.go#L51) and the given example (https://github.com/willfaught/gockle/blob/master/examples_test.go#L54) seems not correct, because it returns `(map[string]interface{}, error)`.

If I add this block at the end of `examples_test.go`

``` go
func TestScanMap(t *testing.T) {
    m := make(map[string]interface{})
    err := mySession.ScanMap("select * from users", m)
    if err != nil {
        t.Fatal(err)
    }
}
```

I have this panic:

``` text
panic: interface conversion: map[string]interface {} is not error: missing method Error [recovered]
    panic: interface conversion: map[string]interface {} is not error: missing method Error

goroutine 5 [running]:
panic(0x77dc00, 0xc820017c00)
    /home/me/go-1.6.1/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc820090090)
    /home/me/go-1.6.1/src/testing/testing.go:467 +0x192
panic(0x77dc00, 0xc820017c00)
    /home/me/go-1.6.1/src/runtime/panic.go:426 +0x4e9
github.com/willfaught/gockle.SessionMock.ScanMap(0xc820011180, 0x3, 0x4, 0x0, 0x1, 0x82d7b0, 0x13, 0xc82000b890, 0x0, 0x0, ...)
    /home/me/go/src/github.com/willfaught/gockle/session.go:132 +0x29a
github.com/willfaught/gockle.TestScanMap(0xc820090090)
    /home/me/go/src/github.com/willfaught/gockle/examples_test.go:61 +0x9a
testing.tRunner(0xc820090090, 0x9ade90)
    /home/me/go-1.6.1/src/testing/testing.go:473 +0x98
created by testing.RunTests
    /home/me/go-1.6.1/src/testing/testing.go:582 +0x892
```

Could you plz provide me a valid example?

Thx in adv

**Comment by willfaught** [comment]
Hi @jerome-laforge, thanks for the feedback! It turns out the example code wasn't being run because there was no output expected. I've tried to address this with the latest commit. Does that fix your issue?

**Comment by willfaught** [comment]
Note that I just pushed a vet fix on top of that, so you want to see HEAD as it is now: 4f254e1

**Comment by jerome-laforge** [comment]
Thx all examples (and specially ExampleIterator_ScanMap()) show me how to mock ScanMap
