### ISSUE TITLE
Ask for examples

### ISSUE THREAD

**Issue by soldiershen** [willfaught/gockle#4]
Dear willfaught,
         I think this framework is very useful who use gocql and wanna to mock the dao level.If you write a n example for readers it will be perfect.Thanks!    Waiting you to save my life.

**Comment by willfaught** [comment]
Hey @soldiershen, I just stumbled on this issue. I'm sorry that I missed it. Not sure how that happened.

I haven't touched this code in a couple years. I think I'm going to leave it as-is. Please feel free to fork it under the license.
